version: '3.7'
services:
  nginx:
    image: nginx:1.21.4-perl
    ports:
      - 80:80
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7.4.26-fpm
    volumes:
      - ./app:/usr/share/nginx/html
